config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accounts
  resources :accounts_totalization_report, only: [:index]
  resources :cost_centers
  resources :entries
  resources :portal
  resources :tags
  resources :universes
  root to: 'portal#index'
end


# Creating a resourceful route will also expose a number of helpers to the controllers in your application. In the case of resources :photos:
# photos_path returns /photos
# new_photo_path returns /photos/new
# edit_photo_path(:id) returns /photos/:id/edit (for instance, edit_photo_path(10) returns /photos/10/edit)
# photo_path(:id) returns /photos/:id (for instance, photo_path(10) returns /photos/10)
# Each of these helpers has a corresponding _url helper (such as photos_url) which returns the same path prefixed with the current host, port, and path prefix.

# group
# namespace :admin do
#   resources :articles, :comments
# end

#assert_generates '/photos/1', { controller: 'photos', action: 'show', id: '1' }

# From the controller's point of view, there are three ways to create an HTTP response:
# Call render to create a full response to send back to the browser
# Call redirect_to to send an HTTP redirect status code to the browser
# Call head to create a response consisting solely of HTTP headers to send back to the browser

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :account
  belongs_to :cost_center
  belongs_to :universe
  has_and_belongs_to_many :tags
  validates :date, presence: true
  validates :value, presence: true, :numericality => { :greater_than => 0 }
  validates :memo, presence: false
  validates :account, presence: true
  validates :cost_center, presence: true
  validates :universe, presence: true
  #tags not required
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    def index
        @entries = Entry.includes(:account, :cost_center, :universe).order(date: :desc)
    end

    def new
        @entry = Entry.new
    end

    def create
        @entry = Entry.create(entry_params)
        if @entry.save
            redirect_to @entry
        else
            render 'new'
        end
    end

    def show
        @entry = load_eagerly(params[:id])
    end

    def edit
        @entry = load_eagerly(params[:id])
    end

    def update
        @entry = Entry.find(params[:id])
        if @entry.update(entry_params)
            redirect_to @entry
        else
            render 'edit'
        end
    end

    def destroy
        if Entry.destroy(params[:id])
            redirect_to 'index'
        else
            render 'show'
        end
    end

    def load_eagerly(id)
        entry = Entry.includes(:account, :cost_center, :universe).find(id)
        return entry
    end

    def entry_params
        params.require(:entry).permit(:date, :value, :memo, :account_id, :cost_center_id, :universe_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_edit_new.html.erb
<% title "#{incoming_title} Entry" %>

<%= form_for @entry, url: {action: incoming_action} do |f| %>

    <% if @entry.errors.any? %>
        <ul>
            <% @entry.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    <table>
        <tr>
            <td><%= f.label :date, 'Date' %></td>
            <td><%= f.date_field :date %></td>
        </tr>
        <tr>
            <td><%= f.label :value, 'Value' %></td>
            <td><%= f.number_field :value, step: 0.01 %></td>
        </tr>
        <td><%= f.label :account, 'Account' %></td>
            <td>
                <%= f.collection_select(:account_id, Account.all, :id, :structure_and_name, { prompt: true }) %>
            </td>
        </tr>
        <td><%= f.label :cost_center, 'Cost Center' %></td>
            <td>
                <%= f.collection_select(:cost_center_id, CostCenter.all, :id, :name, { prompt: true }) %>
            </td>
        </tr>
        <tr>
            <td><%= f.label :memo, 'Memo' %></td>
            <td><%= f.text_area :memo %></td>
        </tr>
        <td><%= f.label :universe, 'Universe' %></td>
            <td>
                <%= f.collection_select(:universe_id, Universe.all, :id, :name, { prompt: true }) %>
            </td>
        </tr>
    </table>
    <%= submit_tag 'Save' %>
<% end %>

<%= link_to "Search", entries_path %>

app/views/entries/edit.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'Edit', incoming_action: 'update' } %>

app/views/entries/index.html.erb
<% title 'Entries' %>

<% if @entries == nil || @entries.length == 0 %>
    <p>No entries found.</p>
    <%= link_to new_entry_path do %>
        <%= image_tag "new_24px.svg", :title => 'New' %>
    <% end %>
<% else %>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Value</th>
                <th scope="col">Account</th>
                <th scope="col">Cost Center</th>
                <th scope="col">Memo</th>
                <th scope="col">Universe</th>
            </tr>
        </thead>
        <tbody>
            <% @entries.each do |e| %>
                <tr>
                    <td><%= e.date %></td>
                    <td><%= e.value %></td>
                    <td><%= e.account.name %></td>
                    <td><%= e.cost_center.name %></td>
                    <td><%= e.memo %></td>
                    <td><%= e.universe.name %></td>
                    <td>
                    <%= render partial: 'layouts/search_item_buttons', locals: { entity: e } %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/entries/new.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'New', incoming_action: 'create' } %>

app/views/entries/show.html.erb
<% title 'Show Entry' %>

<%= form_for @entry do |f| %>
    <table>
        <tr>
            <th>Date</td>
            <td><%= @entry.date %></td>
        </tr>
        <tr>
            <th>Value</td>
            <td><%= @entry.value %></td>
        </tr>
        <tr>
            <th>Account</td>
            <td><%= @entry.account.name %></td>
        </tr>
        <tr>
            <th>Cost Center</td>
            <td><%= @entry.cost_center.name %></td>
        </tr>
        <tr>
            <th>Memo</td>
            <td><%= @entry.memo %></td>
        </tr>
        <tr>
            <th>Universe</td>
            <td><%= @entry.universe.name %></td>
        </tr>
    </table>
<% end %>

<%= render partial: 'layouts/search_item_buttons', locals: { entity: @entry } %>