config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accounts
  resources :accounts_totalization_report, only: [:index]
  resources :cost_centers
  resources :entries
  resources :portal
  resources :tags
  resources :universes
  root to: 'portal#index'
end


# Creating a resourceful route will also expose a number of helpers to the controllers in your application. In the case of resources :photos:
# photos_path returns /photos
# new_photo_path returns /photos/new
# edit_photo_path(:id) returns /photos/:id/edit (for instance, edit_photo_path(10) returns /photos/10/edit)
# photo_path(:id) returns /photos/:id (for instance, photo_path(10) returns /photos/10)
# Each of these helpers has a corresponding _url helper (such as photos_url) which returns the same path prefixed with the current host, port, and path prefix.

# group
# namespace :admin do
#   resources :articles, :comments
# end

#assert_generates '/photos/1', { controller: 'photos', action: 'show', id: '1' }

# From the controller's point of view, there are three ways to create an HTTP response:
# Call render to create a full response to send back to the browser
# Call redirect_to to send an HTTP redirect status code to the browser
# Call head to create a response consisting solely of HTTP headers to send back to the browser

app/models/cost_center.rb
class CostCenter < ApplicationRecord
  belongs_to :universe
  validates :structure, presence: true, 
                        length: {maximum:64, too_long: "%{count} characters is the maximum allowed"},
                        format: { with: /[0-9]+(\.[0-9]+)*/, message: "Structure is something like 1.01.001" }
  validates :name, presence: true, 
                   length: {maximum:255, too_long: "%{count} characters is the maximum allowed"}
end

app/controllers/cost_centers_controller.rb
class CostCentersController < ApplicationController
    def index
        @cost_centers = CostCenter.includes(:universe).order(structure: :asc)
    end

    def new
        @cost_center = CostCenter.new
    end

    def create
        @cost_center = CostCenter.new(cost_center_params)
        if @cost_center.save
            redirect_to @cost_center
        else
            render 'new'
        end
    end

    def show
        @cost_center = CostCenter.includes(:universe).find(params[:id])
    end

    def edit
        @cost_center = CostCenter.includes(:universe).find(params[:id])
    end

    def update
        @cost_center = CostCenter.find(params[:id])
        if @cost_center.update(cost_center_params)
            redirect_to @cost_center
        else
            render 'update'
        end
    end

    def destroy
        @cost_center = CostCenter.destroy(params[:id])
        #TODO if?
        render 'index'
    end

    private
    def cost_center_params
        params.require(:cost_center).permit(:structure, :name, :universe_id)
    end
end

app/views/cost_centers/_edit_new.html.erb
<% title "#{incoming_title} Cost Center" %>

<%= form_for @cost_center, url: {action: incoming_action} do |f| %>

    <% if @cost_center.errors.any? %>
        <ul>
            <% @cost_center.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    <table>
        <tr>
            <td><%= f.label :structure, 'Structure' %></td>
            <td><%= f.text_field :structure %></td>
        </tr>
        <tr>
            <td><%= f.label :name, 'Name' %></td>
            <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <td><%= f.label :universe, 'Universe' %></td>
            <td>
                <%= f.collection_select(:universe_id, Universe.all, :id, :name, { prompt: true }) %>
            </td>
        </tr>
    </table>
    <%= submit_tag 'Save' %>
<% end %>

<%= link_to "Search", cost_centers_path %>

app/views/cost_centers/edit.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'Edit', incoming_action: 'update' } %>

app/views/cost_centers/index.html.erb
<% title 'Cost Centers' %>

<% if @cost_centers == nil || @cost_centers.length == 0 %>
    <p>No cost_centers found.</p>
    <%= link_to new_cost_center_path do %>
        <%= image_tag "new_24px.svg", :title => 'New' %>
    <% end %>
<% else %>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th scope="col">Structure</th>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            <% @cost_centers.each do |u| %>
                <tr>
                    <td><%= u.structure %></td>
                    <td><%= u.name %></td>
                    <td>
                    <%= render partial: 'layouts/search_item_buttons', locals: { entity: u } %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/cost_centers/new.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'New', incoming_action: 'create' } %>

app/views/cost_centers/show.html.erb
<% title 'Show Cost Center' %>

<%= form_for @cost_center do |f| %>
    <table>
        <tr>
            <th>Structure</td>
            <td><%= @cost_center.structure %></td>
        </tr>
        <tr>
            <th>Name</td>
            <td><%= @cost_center.name %></td>
        </tr>
    </table>
<% end %>

<%= render partial: 'layouts/search_item_buttons', locals: { entity: @cost_center } %>