config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accounts
  resources :accounts_totalization_report, only: [:index]
  resources :cost_centers
  resources :entries
  resources :portal
  resources :tags
  resources :universes
  root to: 'portal#index'
end


# Creating a resourceful route will also expose a number of helpers to the controllers in your application. In the case of resources :photos:
# photos_path returns /photos
# new_photo_path returns /photos/new
# edit_photo_path(:id) returns /photos/:id/edit (for instance, edit_photo_path(10) returns /photos/10/edit)
# photo_path(:id) returns /photos/:id (for instance, photo_path(10) returns /photos/10)
# Each of these helpers has a corresponding _url helper (such as photos_url) which returns the same path prefixed with the current host, port, and path prefix.

# group
# namespace :admin do
#   resources :articles, :comments
# end

#assert_generates '/photos/1', { controller: 'photos', action: 'show', id: '1' }

# From the controller's point of view, there are three ways to create an HTTP response:
# Call render to create a full response to send back to the browser
# Call redirect_to to send an HTTP redirect status code to the browser
# Call head to create a response consisting solely of HTTP headers to send back to the browser

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :entries

  validates :name, presence: true, 
                   length: {maximum:255, too_long: "%{count} characters is the maximum allowed"}
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.order(name: :asc)
    end

    def new
        @tag = Tag.new
    end

    def create
        @tag = Tag.create(tag_params)
        if @tag.save
            redirect_to @tag
        else
            render 'new'
        end
    end

    def show
        @tag = Tag.find(params[:id])
    end

    def edit
        @tag = Tag.find(params[:id])
    end

    def update
        @tag = Tag.find(params[:id])
        if @tag.update(tag_params)
            redirect_to @tag
        else
            render 'update'
        end
    end

    def destroy
        if Tag.destroy(params[:id])
            render 'index'
        else
            render 'show'
        end
    end

    private
    def tag_params
        params.require(:tag).permit(:id, :name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_edit_new.html.erb
<% title "#{incoming_title} Tag" %>

<%= form_for @tag, url: {action: incoming_action} do |f| %>

    <% if @tag.errors.any? %>
        <ul>
            <% @tag.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    <table>
        <tr>
            <td><%= f.label :name, 'Name' %></td>
            <td><%= f.text_field :name %></td>
        </tr>
    </table>
    <%= submit_tag 'Save' %>
<% end %>

<%= link_to "Search", tags_path %>

app/views/tags/edit.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'Edit', incoming_action: 'update' } %>

app/views/tags/index.html.erb
<% title 'Tags' %>

<% if @tags == nil || @tags.length == 0 %>
    <p>No tags found.</p>
    <%= link_to new_tag_path do %>
        <%= image_tag "new_24px.svg", :title => 'New' %>
    <% end %>
<% else %>
    <table class="table table-responsive table-striped">
        <thead>
            <tr><th scope="col">Name</th></tr>
        </thead>
        <tbody>
            <% @tags.each do |tag| %>
                <tr>
                    <td><%= tag.name %></td>
                    <td>
                    <%= render partial: 'layouts/search_item_buttons', locals: { entity: tag } %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/tags/new.html.erb
<%= render partial: 'edit_new', locals: { incoming_title: 'New', incoming_action: 'create' } %>

app/views/tags/show.html.erb
<% title 'Show Tag' %>

<%= form_for @tag do |f| %>
    <table>
        <tr>
            <th>Name</td>
            <td><%= @tag.name %></td>
        </tr>
    </table>
<% end %>

<%= render partial: 'layouts/search_item_buttons', locals: { entity: @tag } %>